dependency_cmake_options: ecmwf/ecflow: "-DENABLE_ALL_TESTS=ON -DBOOST_ROOT=${BOOST_ROOT_DIR} -DBOOST_INCLUDEDIR=${BOOST_INCLUDE_DIR} -DBOOST_LIBRARYDIR=${BOOST_LIB_DIR} -DOPENSSL_ROOT_DIR=${OPENSSL_ROOT_DIR} -DENABLE_STATIC_BOOST_LIBS=OFF"
dependencies: |
  ecmwf/ecbuild
  ecmwf/ecflow
dependency_branch: develop
parallelism_factor: 8
self_build: false # Only for python packages
