build:
  modules:
    - boost/1.84.0
    - ninja
    - python3/3.11.8-01
    - qt
    - cmake/new
  dependencies:
    - ecmwf/ecbuild@develop
    - ecmwf/ecflow@develop
  parallel: 64
  pytest_cmd: pytest -rx
