
channels:
  - conda-forge

dependencies:
  - python
  - pip
  - jupyterlab
  - ecflow >= 5.13
  - jinja2
  - requests
  - pytest
  - pygraphviz
  - pip:
    - findlibs

variables:
  QT_MAC_WANTS_LAYER: 1
