name: on-push

on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install .

  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Conda check
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Install pyflow and test
        shell: bash -l {0}  # required to load conda I think
        run: |
          python -m pip install .
          pytest

  distribution:
    runs-on: ubuntu-latest
    needs: [integration-tests, type-check, documentation]

    steps:
    - uses: actions/checkout@v3
    - name: Build distributions
      run: |
        $CONDA/bin/python -m pip install build
        $CONDA/bin/python -m build
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs:
    - pre-commit
    - unit-tests
    - type-check
    - documentation
    - integration-tests
    - distribution
    if: always()
    steps:
    - name: Send Teams notification
      uses: ecmwf-actions/notify-teams@v1
      with:
        incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
        needs_context: ${{ toJSON(needs) }}